
"use client"
import type { Metadata } from "next";
import  Menu from "../Component/Menu"
import Navbar from "../Component/Navbar"
import Link from "next/link";
 import { useState } from "react";
// import Layout from '../../app/Dashboardfinal/Votedetails/Layout'
import './Lay.css'
import { GrUserAdmin } from "react-icons/gr";
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import { Geist, Geist_Mono } from "next/font/google";

import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Vote app",
//   description: "Generated by create next app",
// };

export default function Dashboardlayout({
  
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  const [showSidebar, setShowSidebar] = useState(true);
  return (
    <div className="h-screen flex">
    <div className="w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%]" style={{backgroundColor:" rgb(52, 58, 64)"}}>
 <Link href='/ ' className="flex items-center text-decoration-none justify-center  lg:justify-start p-4 gap-2" >
        {/* <GrUserAdmin /> */}
        <span className="text-gray-400  font-bold">Admin </span>
     </Link>
   <div className={` sidebar transition-all ${showSidebar ? 'sidebar-show' : 'sidebar-hide'}`}>
   <Menu/>
   </div>

    
    </div>
    {/* gowtham */}
     <div className="w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%]  overflow-scroll">

<Navbar/>
     {children}
     </div>
    
      </div>
     
     
  );
}
