
"use client"
import type { Metadata } from "next";
import  Menu from "../Component/Menu"
import Navbar from "../Component/Navbar"
import Link from "next/link";
import Chatpage from "./Chatpag/Chatpage";
 import { useState } from "react";
// import Layout from '../../app/Dashboardfinal/Votedetails/Layout'

import { GrUserAdmin } from "react-icons/gr";
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import { Geist, Geist_Mono } from "next/font/google";
import './Layout.scss'


import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Vote app",
//   description: "Generated by create next app",
// };

export default function Dashboardlayout({
  
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{

  return (
    // style={{backgroundColor:" rgb(52, 58, 64)"}}
    <div className="h-screen flex">
    <div className="gow md:w-[8%] lg:w-[16%] xl:w-[14%] "   >
      <Link href='/' className="flex items-center text-decoration-none justify-center  lg:justify-start p-4 gap-2" >
         <img src="/ai.png" height={30} width={30} alt="" />
        <span className="">Gowtham AI</span>
     </Link>
   <div  className="">
   {/* <Menu/> */}
     <Chatpage/>
   </div>

    
    </div>
    {/* gowtham */}
     <div className=" width-left md:w-[92%] lg:w-[84%] xl:w-[86%] no-scrollbar overflow-scroll overflow-x-hidden">

    <Navbar/>
     {children}
     </div>
    
      </div>
     
     
  );
}
